### ISSUE TITLE
Obtaining and preparing the dataset.

### ISSUE THREAD

**Issue by jjdredd** [MaliParag/ICDAR2019#2]
Hello.
Thank you for the valuable work creating this dataset. I have several questions:

1. Do I understand correctly that I'll have to download most of the articles in the dataset one-by one
using the corresponding links in the text file from the EasyDownload directory?

2. It seems after downloading the articles, their file names differ from the names of the corresponding csv and in file size listings. Is there a script to batch-rename them or should I rename them according to their title/author/journal/year using common sense?

3. Are there any other similar datasets? GTDB seems to be character-level, while I need expression-level bounding boxes.

**Comment by MaliParag** [comment]
Hi,

1. You need to download articles on your own as we can not provide them because of copyright issues.

2. Please download the articles  using  text files in the EasyDownload directory 

"GTDB_18files.txt": These 18 documents can be downloaded easily from command line : wget -P [outputDir] -i GTDB_18files.txt 

"GTDB_29files.txt": for the rest of the articles you need to check the URLs and download them from there.

I will probably add the name the file should be renamed to. But, for now, use common sense as there is no clash in the author's name and journal year. 

3. TFD-ICDAR datasets in this repository provide bounding boxes for the math expressions. I do not know of any other dataset that provides bounding boxes for both embedded and displayed math expressions. I will update here if I find one.

**Comment by jjdredd** [comment]
Thanks much for the reply. I think I have dealt with the issue 2 successfully with scripts:

https://github.com/jjdredd/TFD-ICDAR2019/blob/master/TFD-ICDAR2019v2/file_download_names_18.script.txt

https://github.com/jjdredd/TFD-ICDAR2019/blob/master/TFD-ICDAR2019v2/file_download_names_29.script.txt
